spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academy?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  logging:
    level:
      org:
        hibernate:
          type: trace